var fName = {
	"a": "Creepy",
	"b": "Deadly",
	"c": "Eerie",
	"d": "Howling",
	"e": "Icy",
	"f": "Invisible",
	"g": "Jumpy",
	"h": "Dark",
	"i": "Savage",
	"j": "Quiet",
	"k": "Grim",
	"l": "Dangerous",
	"m": "Cursed",
	"n": "Frightful",
	"o": "Bitter",
	"p": "Gloomy",
	"q": "Menacing",
	"r": "Cackling",
	"s": "Wicked",
	"t": "Phantom",
	"u": "Scarlet",
	"v": "Haunted",
	"w": "Gloomy",
	"x": "Magical",
	"y": "Lurking",
	"z": "Grave"
};

var mName = {
	" ": "",
	"a": "Potion",
	"b": "Zombie",
	"c": "Ghoul",
	"d": "Vampire",
	"e": "Silver",
	"f": "Spooky",
	"g": "Bat",
	"h": "Fairy",
	"i": "Candy",
	"j": "Goblin",
	"k": "Spider",
	"l": "Broomstick",
	"m": "Pumpkin",
	"n": "Nightmare",
	"o": "Monster",
	"p": "Skull",
	"q": "Mummy",
	"r": "Shadow",
	"s": "Troll",
	"t": "Owl",
	"u": "Fog",
	"v": "Ghost",
	"w": "Cat",
	"x": "Boogey",
	"y": "Mist",
	"z": "Night"
};

var lName = {
	" ": "",
	"a": "Stalker",
	"b": "Breaker",
	"c": "Heart",
	"d": "Eater",
	"e": "Lover",
	"f": "Finder",
	"g": "Crafter",
	"h": "Dreamer",
	"i": "Giver",
	"j": "Tamer",
	"k": "Catcher",
	"l": "Hunter",
	"m": "Giver",
	"n": "Runner",
	"o": "Stealer",
	"p": "Walker",
	"q": "Eyes",
	"r": "Doctor",
	"s": "Crafter",
	"t": "Caller",
	"u": "Eater",
	"v": "Weaver",
	"w": "Finder",
	"x": "Weaver",
	"y": "Caster",
	"z": "Duster"
};
